#include "embedded_files/EmbeddedFileTable.hpp"

#include "logger/Logger.hpp"

#include <cstring>

namespace embedded_files {

static logger::Logger log{"EmbeddedFileTable"};

// ------------------------------------------------------------
// Linker symbols generated by EMBED_FILES
// ------------------------------------------------------------
// Top-level UI

extern const uint8_t _binary__favicon_ico_start[] asm("_binary__favicon_ico_start");
extern const uint8_t _binary__favicon_ico_end[] asm("_binary__favicon_ico_end");

// Provisioning UI
extern const uint8_t _binary_provision_index_html_start[] asm("_binary_provision_index_html_start");
extern const uint8_t _binary_provision_index_html_end[] asm("_binary_provision_index_html_end");

extern const uint8_t _binary_provision_app_js_start[] asm("_binary_provision_app_js_start");
extern const uint8_t _binary_provision_app_js_end[] asm("_binary_provision_app_js_end");

extern const uint8_t _binary_provision_ui_js_start[] asm("_binary_provision_ui_js_start");
extern const uint8_t _binary_provision_ui_js_end[] asm("_binary_provision_ui_js_end");

// Runtime UI
extern const uint8_t _binary_runtime_index_html_start[] asm("_binary_runtime_index_html_start");
extern const uint8_t _binary_runtime_index_html_end[] asm("_binary_runtime_index_html_end");

extern const uint8_t _binary_runtime_app_js_start[] asm("_binary_runtime_app_js_start");
extern const uint8_t _binary_runtime_app_js_end[] asm("_binary_runtime_app_js_end");

// Common shared JS/CSS
extern const uint8_t _binary_common_api_js_start[] asm("_binary_common_api_js_start");
extern const uint8_t _binary_common_api_js_end[] asm("_binary_common_api_js_end");

extern const uint8_t _binary_common_ui_js_start[] asm("_binary_common_ui_js_start");
extern const uint8_t _binary_common_ui_js_end[] asm("_binary_common_ui_js_end");

extern const uint8_t _binary_common_modal_js_start[] asm("_binary_common_modal_js_start");
extern const uint8_t _binary_common_modal_js_end[] asm("_binary_common_modal_js_end");

extern const uint8_t _binary_common_state_js_start[] asm("_binary_common_state_js_start");
extern const uint8_t _binary_common_state_js_end[] asm("_binary_common_state_js_end");

extern const uint8_t _binary_common_styles_css_start[] asm("_binary_common_styles_css_start");
extern const uint8_t _binary_common_styles_css_end[] asm("_binary_common_styles_css_end");

// ------------------------------------------------------------
// Static table of embedded files
// ------------------------------------------------------------
struct FileEntry {
    const char *path;
    const uint8_t *start;
    const uint8_t *end;
};

static const FileEntry files[] = {
    // Top‑level UI
    {"/favicon.ico", _binary__favicon_ico_start, _binary__favicon_ico_end},

    // Provisioning UI
    {"/provision/app.js", _binary_provision_app_js_start, _binary_provision_app_js_end},
	{"/provision/ui.js", _binary_provision_ui_js_start, _binary_provision_ui_js_end},
    {"/provision/index.html", _binary_provision_index_html_start, _binary_provision_index_html_end},

    // Runtime UI
    {"/runtime/index.html", _binary_runtime_index_html_start, _binary_runtime_index_html_end},
    {"/runtime/app.js", _binary_runtime_app_js_start, _binary_runtime_app_js_end},

    // Shared JS/CSS
    {"/common/api.js", _binary_common_api_js_start, _binary_common_api_js_end},
    {"/common/ui.js", _binary_common_ui_js_start, _binary_common_ui_js_end},
    {"/common/modal.js", _binary_common_modal_js_start, _binary_common_modal_js_end},
    {"/common/state.js", _binary_common_state_js_start, _binary_common_state_js_end},
    {"/common/styles.css", _binary_common_styles_css_start, _binary_common_styles_css_end},
};

// ------------------------------------------------------------
// Modern API
// ------------------------------------------------------------
const EmbeddedFile *EmbeddedFileTable::find(std::string_view path) const {
    // TODO review logging - probably over the top.
    log.debug("find '%.*s'", (int) path.size(), path.data());

    for (auto &a : files) {
        if (path == a.path) {
            static EmbeddedFile embedded_file;
            embedded_file.data = a.start;
            embedded_file.size = a.end - a.start;
            return &embedded_file;
        }
    }

    log.warn("File not found: '%.*s'", (int) path.size(), path.data());
    return nullptr;
}

// ------------------------------------------------------------
// Legacy API
// ------------------------------------------------------------
const uint8_t *EmbeddedFileTable::find(const char *path, size_t &outSize) const {
    for (auto &a : files) {
        if (std::strcmp(a.path, path) == 0) {
            outSize = a.end - a.start;
            return a.start;
        }
    }

    log.warn("File not found: '%s'", path);
    return nullptr;
}

} // namespace embedded_files